package com.myteam.decisiontablesample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer productPrice;
	private java.lang.String userType;
	private java.lang.Double discount;

	public Product() {
	}

	public java.lang.Integer getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(java.lang.Integer productPrice) {
		this.productPrice = productPrice;
	}

	public java.lang.String getUserType() {
		return this.userType;
	}

	public void setUserType(java.lang.String userType) {
		this.userType = userType;
	}

	public java.lang.Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Double discount) {
		this.discount = discount;
	}

	public Product(java.lang.Integer productPrice, java.lang.String userType,
			java.lang.Double discount) {
		this.productPrice = productPrice;
		this.userType = userType;
		this.discount = discount;
	}

}