package com.demo.guidedtable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vehicle implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String type;

	private java.lang.Float value;

	private java.lang.Integer yearOfManufacture;

	public Vehicle() {
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Float getValue() {
		return this.value;
	}

	public void setValue(java.lang.Float value) {
		this.value = value;
	}

	public java.lang.Integer getYearOfManufacture() {
		return this.yearOfManufacture;
	}

	public void setYearOfManufacture(java.lang.Integer yearOfManufacture) {
		this.yearOfManufacture = yearOfManufacture;
	}

	public Vehicle(java.lang.String type, java.lang.Float value,
			java.lang.Integer yearOfManufacture) {
		this.type = type;
		this.value = value;
		this.yearOfManufacture = yearOfManufacture;
	}

}